# Homework set 5, due Oct 6, 2017 

## 1. LU Decomposition (5pts)
Find the LU decompositions of the following three matrices (no pivoting necessary) and use the results to determine
the determinants

$
\begin{pmatrix}
 2 & 1 \\
 -1 & 2 
\end{pmatrix} 
$ 
   , 
$
 \begin{pmatrix}
 2 & -1 & 0 \\
 -1 & 2 & -1 \\
 0 & -1 & 2 \\
 \end{pmatrix} 
$
   ,
$
 \begin{pmatrix}
 3 & 0 & 0 \\
 -1 & 2 & 0 \\
 2 & 1 & 2 \\
 \end{pmatrix} 
$



In [3]:
from PIL import Image

image = Image.open('LU_decomposition1.png')
image.show()
image = Image.open('LU_decomposition2.png')
image.show()
image = Image.open('LU_decomposition3.png')
image.show()


## 2. QR Algorithm (15pts)

a) Follow the text on page 246-247 which lays out the algorithm to construct a QR decomposition for a $N\times N$ matrix and write a python function for it. Check your result using the following matrix


$$
\begin{pmatrix}
 1 & 4 & 8 & 4 \\
 4 & 2 & 3 & 7 \\
 8 & 3 & 6 & 9 \\
  4 & 7 & 9 & 2 
 \end{pmatrix} 
$$

b) Using your function to write a python program that determines the eigenvalues and eigenvectors of a real-valued symmetric matrix. Test it with the matrix above and test your answers with the appropriate numpy function. 


In [1]:
# -*- coding: utf-8 -*-
"""
Created on Wed Oct  7 02:07:39 2020
@author: Suzanne Conejos
"""
import numpy as np
from numpy import array
from numpy.linalg import eigh


#Using numpy.linalg.norm to get norm |u|
def q(u):
    norm = np.linalg.norm(u)
    q = []
    for i in range (0, len(u)):
        q.append((1/norm)*u[i])
    return np.array(q)

def printM(m):
    for i in range(0, len(m)):
        print (m[i])

def decompose(A):
    
    w = h = len(A)
    aVals = []
    uVals = []
    qVals = []

    Q = np.zeros((h,w),float)
    R = np.zeros((h,w),float)
    
    #Get values of A0 to An
    for i in range(0,w):
        temp = []
        for j in range(0,h):
            temp.append(A[j][i]);                    
        aVals.append(temp)
        
    #Get values of q using Gram-Schmidt process
    for i in range(0,w):
        #for i == 0, u0 = A0
        if (i == 0):
            u = np.array(aVals[i])
            uVals.append(u)
            qVals.append(q(u))
        else:
            #get Ui
            u = aVals[i]
            for j in range(1,i+1):
                u = np.subtract(u, np.dot(np.dot(aVals[i], qVals[j - 1]), qVals[j-1]))
            uVals.append(u)
            qVals.append(q(u))
                
    #Create Q using qVals
    for i in range(0,w):
        for j in range(0,h):
            Q[j][i] = qVals[i][j]
    #print("============================")            
    #print("Matrix Q")
    #printM (Q)  
    #print("============================")
    
    #Create R
    for i in range(0,h):
        for j in range(i,w):
            R[i][j] = np.dot(aVals[j], qVals[i]) 
    #print("============================")
    #print("Matrix R")     
    #printM (R)  
    #print("============================")

    #print("============================")
    #print("Matrix QR") 
    #printM(np.dot(Q,R))          
    #print("============================")
    
    #Calculating eigenvalues and eigenvectors
    B = array(A, float)
    x,V=eigh(B)    
    #print("Eigenvalues") 
    #print(x)
    #print("Eigenvectors") 
    #print(V)
    #print("============================")
    
    return ("Matrix",A,"Q",Q,"R",R,"Matrix QR",np.dot(Q,R),"Eigenvalues",x,"Eigenvectors",V)

"""
Testing Function
"""

A = [[1, 4, 8, 4],
     [4, 2, 3, 7],
     [8, 3, 6, 9],
     [4, 7, 9, 2]]

decompose(A) 


('Matrix',
 [[1, 4, 8, 4], [4, 2, 3, 7], [8, 3, 6, 9], [4, 7, 9, 2]],
 'Q',
 array([[ 0.10153462,  0.558463  ,  0.80981107,  0.1483773 ],
        [ 0.40613847, -0.10686638, -0.14147555,  0.8964462 ],
        [ 0.81227693, -0.38092692,  0.22995024, -0.37712564],
        [ 0.40613847,  0.72910447, -0.5208777 , -0.17928924]]),
 'R',
 array([[ 9.8488578 ,  6.49821546, 10.55960012, 11.37187705],
        [ 0.        ,  5.98106979,  8.4234836 , -0.484346  ],
        [ 0.        ,  0.        ,  2.74586406,  3.27671222],
        [ 0.        ,  0.        ,  0.        ,  3.11592335]]),
 'Matrix QR',
 array([[1., 4., 8., 4.],
        [4., 2., 3., 7.],
        [8., 3., 6., 9.],
        [4., 7., 9., 2.]]),
 'Eigenvalues',
 array([-8., -3.,  1., 21.]),
 'Eigenvectors',
 array([[-0.38357064, -0.77459667,  0.25819889, -0.43151697],
        [ 0.43151697, -0.25819889, -0.77459667, -0.38357064],
        [ 0.52740963,  0.25819889,  0.51639778, -0.62330229],
        [-0.62330229,  0.51639778, -0.25819889, -


# 3. Chain of Resistors (10pts)

Consider a long chain of resistors wired up like this

<img src="resistor-network.jpg" alt=" " style="width:504px;height:208px;">

All resistors have the same resistane $R$. The battery delivers a voltage of $5V$. Find the voltages at the other internal points of the circuit. 

a) Using Ohm's law and Kirchhoff's current law, which says that the total net current out of any junction in a circuit must be zero (otherwise charges would accumulate there) to show that the voltages $V_1,V_2,\ldots,V_N$ satisfy the linear set of equations

$$
\begin{align}
 3V_1 - V_2 - V_3 &= V_+  \\
 -V_1 + 4V_2 - V_3 - V_4 &= V_+ \\
 & \vdots \\
-V_{i-2} - V_{i-1} + 4V_i - V_{i+1} - V_{i+2}  &= 0 \\ 
 & \vdots \\
-V_{N-3} - V_{N-2} + 4V_{N-1} - V_N &= 0 \\
-V_{N-2} - V_{N-1} +3V_N &= 0  
\end{align}
$$

Express these equations in vector form ${\bf A}{\bf V} = {\bf b}$ and find the coefficients of the matrix ${\bf A}$ and vector ${\bf b}$. 

b) Write a Python program to solve for the voltages $V_i$ with a number of 10 nodes.

c) For larger number of nodes use the library-based function solve_banded to sove the equations above. Remember that you have to rewrite the coefficient matrix for that routine as described in your class notes. The Scipy document also provides an example which you can use as starting point. Solve for the voltages for 10000 nodes.



In [54]:
from PIL import Image

image = Image.open('resistor1.jpg')
image.show()
image = Image.open('resistor2.jpg')
image.show()

In [35]:
# -*- coding: utf-8 -*-
"""

"""
from numpy.linalg import solve
from numpy import  array

# Test with 10 elements

NumNodes = 10  #no. of nodes
Volt = 5   #given voltage

A = array([
	[3, -1, -1, 0, 0, 0, 0, 0, 0, 0],
	[-1, 4, -1, -1, 0, 0, 0, 0, 0, 0],
	[-1,-1, 4, -1, -1, 0, 0, 0, 0, 0],
	[0, -1,-1, 4, -1, -1, 0, 0, 0, 0],
	[0, 0, -1,-1, 4, -1, -1, 0, 0, 0],
	[0, 0, 0, -1,-1, 4, -1, -1, 0, 0],
	[0, 0, 0, 0, -1,-1, 4, -1, -1, 0],
	[0, 0, 0, 0, 0, -1,-1, 4, -1, -1],
	[0, 0, 0, 0, 0, 0, -1,-1, 4, -1],
	[0, 0, 0, 0, 0, 0, 0, -1, -1, 3]
],float)

v = array([Volt, Volt, 0, 0, 0, 0, 0, 0, 0, 0],float)

x = solve(A,v)
print(x)
print('=========================')


[4.12573674 3.9194499  3.45776031 3.09430255 2.69155206 2.30844794
 1.90569745 1.54223969 1.0805501  0.87426326]


In [52]:
# -*- coding: utf-8 -*-
import numpy as np
from scipy.linalg import solve_banded

# Banded example

NumNodes = 10000
Volt = 5
Ab = zeros((5,NumNodes),float)

vb = zeros(NumNodes,float)

vb[[0,1]] = Volt
#print(vb)
Ab[:,:] = -1
#print(Ab)
Ab[2,:] = 4
#print(Ab)
Ab[2,0] = 3
#print(Ab)
Ab[2,NumNodes-1] = 3
#print(Ab)

x = solve_banded((2,2),Ab,vb)
print(x)

[4.99888228e+00 4.99861842e+00 4.99802841e+00 ... 1.97158611e-03
 1.38158071e-03 1.11772227e-03]
